import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SKhan (ツ)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/programmer.png" sizes="any" />
      </head>
      <body
        className="flex justify-center items-center h-screen bg-gradient-to-br from-yellow-100 to-green-100 font-mono px-3"
      >
        {children}
      </body>
    </html>
  );
}
